# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hunter Maximillion Monk
email: hunter@huntermonk.com
description: This is the personal website for Hunter Maximillion Monk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://huntermonk.com" # the base hostname & protocol for your site
twitter_username: huntermmonk
github_username: huntermonk
timezone: America/Los_Angeles

google_analytics: UA-81364105-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM

plugins: [jekyll-feed]
